[project]
name = "mmr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepface>=0.0.96",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "mediapipe>=0.10.21",
    "numpy>=1.26.4",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.3",
    "yt-dlp>=2025.11.12",
]
